apiVersion: v1
kind: PersistentVolume
metadata:
  name: php-app-dev2-volume
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /data/php-app-logs
