apiVersion: v1
kind: PersistentVolume
metadata:
  name: php-app-logs-dev1
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /data/php-app-logs
