apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: php-app-logs
  namespace: php-app-dev1
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: manual
  resources:
    requests:
      storage: 1Gi
  volumeName: php-app-logs-dev1
